### PR TITLE
FEATURE: Add curl dependency to container for automated plugin pulling

### PR DESCRIPTION
**Pull request by Matthew-Beckett**
This is a dependent PR for https://github.com/MultiPaperK8s/MultiPaperKustomize/pull/1

### CODE REVIEW

**Comment by RemcoSpigot** [comment]
Lgtm, but let’s separate concerns and only add curl to the image and target this PR for master branch.

**Review by RemcoSpigot — CHANGES_REQUESTED** [review]
Please remove the GitHub action change and target merge into master instead

**Comment by Matthew-Beckett** [comment]
> Please remove the GitHub action change and target merge into master instead

Doing so would also merge experimental/aarch64 into master and that is not part of this PR.

**Comment by RemcoSpigot** [comment]
> Please remove the GitHub action change and target merge into master instead

This on top of moving this PR to target `experimental/multi-os`. Or feel free to add the code directly into this branch :)
Approved as it's not going to impose any risk other than users downloading wrong packages themselves during initialisation.

**Pull request closed without merging**
